- name: Check Resource Group (RG)
  shell: |
    az group exists --name miRGAnsible
  register: rg_exists_status

- name: Print result RG
  debug:
    msg: "El RG existe?: {{ rg_exists_status }}"

- name: Create RG
  azure_rm_resourcegroup:
    name: miRGAnsible
    location: eastus2
  when: rg_exists_status.stdout|bool == false
  register: rg_status

- debug:
    msg: "Resultado final RG: {{ rg_status }}"