- name: Check if RG exists first
  shell: |
    az group exists --name  myResourceGroupAnsible
  register: rg_exists_status

- name: "Print RG exists or not"
  debug:
    msg: "El RG existe previamente?: {{ rg_exists_status.stdout }}"

- name: Create resource group
  azure_rm_resourcegroup:
    name: myResourceGroupAnsible
    location: "{{ region.name }}"
  when: rg_exists_status.stdout|bool == false 
  register: rg_status

- debug:
    msg: "{{ rg_status }}"