- name: Create App Service on Linux with Node 18
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ webapp_name }}"
    plan:
      resource_group: "{{ resource_group }}"
      name: "{{ plan_name }}"
      is_linux: true
      sku: F1
    frameworks:
      - name: "node"
        version: "18-lts"
